### ISSUE TITLE
Make website easy to update & modular

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#1]
This week I started creating a bunch of repos to power the [opensourcedesign.net](http://opensourcedesign.net) website. My plan was to use Jekyll to generate the site and various JS libs and Bootsrap on top of that.

I am keenly aware of the pain points @una brings up in her great blog post [The Intimidation Barrier](http://designopen.org/articles/barriers-for-designers/) and how this affects designers looking to contribute to FOSS projects. Una highlights the current **15 steps** it takes to add a simple article to the  [designopen.org](designopen.org) website.

_I've crossed out the steps I was hoping to remove with my process_
1. Stumble upon this [on a public website] page
2. Open the link to Github
3. Have a Github account
4. Know about Github Contribution workflow
5. Fork the Repo
6. ~~Open terminal~~
7. ~~Know that one needs to install dependancies~~
8. ~~Know how to install dependancies~~
9. ~~Know about how Jekyll works~~
10. ~~Run Jekyll server~~
11. Write in markdown or with HTML tags
12. ~~Know about the config file and how to add authors~~
13. Add changes
14. Commit Changes
15. Submit pull request

How to properly minimize designer intimidation is the tricky part. My approach would remove 6 of 15 steps, as they can simply use the Github web browser editor to write in the Markdown content.

Methinks, the trick with this sort of thing is that it must balance:
- Minimizing complex steps for designers
- Not restricting developers to use tools they don't know / prefer
- Strike the right balance of "openness" as both an organization & codebase 
- Keep things small and easy to interact with in a modular way (small different repos)

There's numerous different programming languages, frameworks, and system architectures. I don't know the most ideal approach, but Jeykll (which the @DesignOpen folks are using) feels like a step in the right direction.

I'd argue that designers who want to meaningfully contribute to open source need to learn basic Github flows in order to effectively contribute to projects, Also, a simple tutorial video walking wary designers through the Github workflow and this whole process would be very helpful and achievable, I think!

I'm curious what others think about this approach!

**Comment by jancborchardt** [comment]
Great stuff, I totally agree that striking the right balance is essential. Also +1 on your last paragraph.

**Comment by simonv3** [comment]
So the other day I was playing around with [dat](https://github.com/maxogden/dat) and I was incredibly impressed with the [contribution/explanation/start up](http://maxogden.github.io/get-dat/) flow that they have created there.

Basically they're spinning up a docker instance which installs dat on it and walks people through the process of "programming" with it.

For OpenFarm we're also looking at Docker to create container Ruby apps to make development by non-ruby devs easier. [RubyConf talk on it](https://www.youtube.com/watch?v=SGyLjrY3LJo). And an [article on it](http://dev.chaione.com/rapid-rails-setup-with-docker-and-fig/). Basically compiling the environment of the application so that people can do this without much fuss of installing the right ruby version, elasticsearch, etc.

This got me thinking that maybe it's possible to create something similar to get-dat that is a link (people don't need to open a terminal) which gives them two or three windows with step by step instructions. Ideally it's also running gulp watch as a background process so that they can see the updates lives.

What I see that doing is that people access the URL and are making changes without any of the scary stuff. A pain point here is still github accessing, but we might be able to figure that out?

**Comment by simonv3** [comment]
I'm going to add a link to [prose.io](http://prose.io) here, which is a simple way of editing text files etc.

**Comment by jdittrich** [comment]
Totally agree with *Making the  website easy to update & modular*. I think as well that the crossed out steps are the most difficult ones and thus should be avoided first. 

I like the idea to use something like prose.io (as far as I can evaluate this for now); as well the use of the GitHub interface itself for editing is a good idea. Learning local-repo based git is not too hard, but by no means a nice onboarding of new, not-(yet-)programming-savvy contributors either.

**Comment by simonv3** [comment]
I think prose.io actually does a good job eliminating 4-10, and 12-15, all that you're left with is:

1. Stumble upon this [on a public website] page
2. Open the link to prose.io for [this website](http://prose.io/#opensourcedesign/opensourcedesign.github.io/)
3. Have a Github account
5. Make changes in Markdown or with HTML tags
6. Save changes in Prose

I just noticed that Prose actually lets you start making changes when you're not logged in, but the way that it handles that error is a bit broken (it just says there was a problem, and doesn't tell you to log in). 

Also, apparently if you make too many requests to prose.io you get blocked if you're not logged in.

**Comment by jdittrich** [comment]
@simonv3 what you say about prose seems pretty great, and what’s left seems to be familiar enough even for non-tech-savvy users. 
The problematic behaviour of prose in regards to editing and not being logged in is [discussed in their bug tracker](https://github.com/prose/prose/issues/643)

**Comment by jancborchardt** [comment]
@simonv3 the problem being that Prose doesn’t fork automatically, right? So either you need to be in the opensourcedesign organization or manually fork the repo, then do the changes, and _then_ also issue a pull request. And at that point using the Github built-in editor might be easier. ;)

**Comment by simonv3** [comment]
Oh right, I hadn't considered that. Works great if your workflow doesn't
involve PRs. Dang.

**Comment by jancborchardt** [comment]
Even if it doesn’t involve PRs, any outside contributor – who are kind of the target audience of this method – still need to fork.

**Comment by simonv3** [comment]
From the threat that @jdittrich links, this is interesting: https://github.com/benbalter/comment-card

**Comment by bnvk** [comment]
Super major +1 to prose.io as it seems very much towards this goal. I agree that it *could* help cut out more of these steps... the forking part does provide a problem. Perhaps we create a certain "group" within the GH org and those members don't need to "fork + pull req" and just edit directly?

**Comment by jdittrich** [comment]
could we fork via the api somehow?

**Comment by jancborchardt** [comment]
@bnvk everyone in the org can already edit directly. The pull request process is just something we decided because it increases visibility and transparency for everyone. If we all would just commit directly, it would be very difficult for others in the org to follow the changes. Also, it’s an aspect of doing a review and a bit of quality assurance. :)

**Comment by simonv3** [comment]
@bnvk @jancborchardt And everyone who's in the OS design group can submit edits through prose.io, which would be a direct commit, rather than a fork and pr. However, it must be possible to tweak prose.io (he said, naively) so that it can do a fork and pr, as that's what comment-card and the DesignOpen tools do.

**Comment by bnvk** [comment]
I believe we have a "modular" website that, as long as you except GitHub as an acceptable barrier to entry, is some value of "easy" to update, so closing as it's stagnant!
