### ISSUE TITLE
Turn jobs, events, and similar repos into just data repos

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/opensourcedesign.github.io#159]
I've got an idea for making our site a bit easier to manage that doesn't involve hosting it on our own platform and server.

We can put anything that's "website" in our website repo - templates, indexes, etc and use the `jobs` and `events` repos as purely data repositories that we post to from our various forms, and then use them as JSON or XML endpoints for our website. That way on our website we can do just a simple ajax request to fetch them. 

This way all of our styles and views are in one place. This is not the case right now and makes developing a bit of a pain as long as we're constrained around GitHub as our host and with no one who can take on the sysadmin part of that job.

For search reasons on static sites this is something we should do anyway, but the main downside is that this way there's no easy way to "filter" data before we display it. I think every request we make would have to fetch the entire json object of all the jobs. 

Is this a bad idea? Anyone know if it's do-able?

**Comment by bnvk** [comment]
@simonv3 I think this is what I have been doing already... the problem is
you need to make Jekyll generate JSON, which you need a "layout" for.

Both the Jobs and Events repo's have "dev" branches whereby I've already
turned them into "data repos" and the scripts/install.sh will put them in
the right place to make it all work, but you need to make it choose "dev" 
branches instead of "master"

**Comment by simonv3** [comment]
Ohohoh! Interesting.

What I had in mind more than having the jobs in markdown with frontmatter was to insert them using yaml or something similar when creating them with staticman, but this looks like it might work too. I'm looking in scripts/install.sh though it's not immediately clear to me where it puts them in the right place?
