### ISSUE TITLE
Proposed front page layouts

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/opensourcedesign.github.io#17]
This version is more up front, targeted, and almost a marketing site:
![website-sketch](https://cloud.githubusercontent.com/assets/485583/7840226/a3891028-0496-11e5-9714-45d452c16aa3.png)

One interesting thing to explore here is to maybe include little facts for each section (300 commits, 299 members, 400 tweets, 13 open jobs, etc)

This version is more functional:
![website-sketch-2](https://cloud.githubusercontent.com/assets/485583/7840243/b2fbc19a-0496-11e5-9a13-e162502f9539.png)

**Comment by jdittrich** [comment]
assuming that this page would be the first contact for anyone who might be interested I assume the 1st ("marketing") is the way to go. 

We could as well experiment with combinations of the strength of both layouts – what about the 1st with a footer that holds some current links (like the main section of the 2nd) for those who read that far, like on https://www.libreoffice.org/ ?

**Comment by Xaviju** [comment]
Nice!
I would go with the marketing site since I think open source design still needs a presentation and purposes page because a lot of designers still don't understand very well the concept.
I would go too with minimal information and links, short text and visuals and then a functional version on the secondary level links. :cool:

**Comment by simonv3** [comment]
I'll tinker! Be back at the end of the day.

**Comment by ScintillaLuz** [comment]
hello!!!
Cool :)

My feedback: I like the structure of the second, since I feel it's more organized and the user can just jump from one block to the other without losing anything. The first one doesn't convince me because it gives a "funnel" or a direction (from top to bottom) that I don't see it reflects the content/mission, since if I get it right it's more on informing/getting interested than signup/contact.

The second one also still has the potential to be as bold as the first if the part underneath the line, "Open source design is a group..." would become a full width banner, maybe actually including the text that there's in the first one, that one that says "We provide resources, list jobs, ..." because it's a great text that could satisfy and catch the visitor right away.

But that's just my perspective!!!

**Comment by bnvk** [comment]
@simonv3 nicely done! What about doing BOTH. Have the top of the site (above the fold) contain the big "marketing" style call to actions, each one could link to the more detailed blurb below?

**Comment by jancborchardt** [comment]
Yeah, agree with the previous comments - we need a combination here. The current site does that quite well already, maybe we just iterate on that?

**Comment by simonv3** [comment]
@jancborchardt The reason for this, in my mind, is that it helps architect the site a bit, and it'll give @ScintillaLuz a framework to work within and apply a more unique visual style, which she's offered to explore (yay!). That way we have a clear direction rather than just iterating towards an unknown goal. We can always continue to tweak and iterate beyond that. Let me know if that works for you.

Update taking features from both:
![website-combo](https://cloud.githubusercontent.com/assets/485583/7868807/b5c45bec-057e-11e5-88a9-b846cdfe7a2e.png)

**Comment by jancborchardt** [comment]
@simonv3 the big generic "what is this?" header we can remove. :) Instead we should make the "We are a group ..." a bit bigger. Also - clarify we are not only _interested_ and also work on design.

That's what the current 2 sentences do a pretty good job at and I'm not sure we need to adjust the wording there:
![opensourcedesign](https://cloud.githubusercontent.com/assets/925062/7871952/05d26646-0594-11e5-88e6-152094e3ff25.png)

**Comment by simonv3** [comment]
:+1: agreed. I'll mock something up hopefully later today, definitely this weekend.

**Comment by Xaviju** [comment]
Wow, that last wireframe looks really great :smile:

**Comment by MariekevC** [comment]
Great to see this developing :-)
This discussion made me do this:

![osdesign_fronttop](https://cloud.githubusercontent.com/assets/6065633/7885816/6c85de3a-0626-11e5-89b3-0200dbf476e1.png)

My thoughts for the top frontpage: when you want to invite for collaboration, be as bold and clear about it as possible. 

And watching the open source icon change into a large dot, started this:

![osdesign_grey](https://cloud.githubusercontent.com/assets/6065633/7885828/7d88d1f6-0626-11e5-9bf2-445c4e340c67.png)
![osdesign_sino](https://cloud.githubusercontent.com/assets/6065633/7885829/808510ea-0626-11e5-923a-842f812e6671.png)

The trigger was to combine the open source icon with the design part. 
OSDesign represents the Design part (...) of the Open Source universe, use the image that's already known and add to it,  as in add design to open source.

**Comment by jancborchardt** [comment]
@MariekevC good on the mockup :)

As for the logo - I guess we should try to keep it logo-ish, without any text needed, no?

**Comment by simonv3** [comment]
So here's the concept based on what you suggested @jancborchardt:

![website-sketch-3](https://cloud.githubusercontent.com/assets/485583/7899164/1ec6b590-0719-11e5-98ca-3ef00add975c.png)

@MariekevC I like what you're getting at! Thanks for putting forward some ideas :). 

It took me a moment to realize that it said "You" in one of the titles. I wonder if the logo's location is detracting from the text around it - I'm more drawn to shape of the layout then the actual content. Could you play around with spacing maybe? And in this sense, maybe it makes sense to have a more direct call to action underneath each section (both the You and the Open Source Design)? Even if it only links to another part of the page. Let me know your thoughts on those things!

Side note: I just used the large dot as a placeholder for the logo. I want to give the people doing a visual version of this some leeway, not to feel stuck with with Open Source O (cc @ScintillaLuz)

**Comment by jdittrich** [comment]
Maybe the 1 column, 3 column, 1column,  2 column (from the top) Structure is visually a bit restless. What about having three col. at the bottom: *Activity* , *Interests* and *Get in Touch* (or any other change that provides a more consistent grid)

**Comment by bnvk** [comment]
@simonv3 that's looking great man. My only thoughts are to make the two paragraphs "We are a community..." and "We provide resources..." side by side instead of on top of each other, I think this will help the "restless" bit that @jdittrich mentions!

**Comment by MariekevC** [comment]
@simonv3 
I can play around with the spacing a bit, as you suggested. Maybe also look at possibilities that @jdittrich and @bnvk suggested?

The logo is in the middle as a focal point. From here the reader can choose what is of interest at that moment (instead of scrolling - menu, logo, content, contact).
A starting point which connects things - visually, information, invite, sharing, collaboration, etc. -. 
But it can use a bit more space and maybe softening the tone to a grey makes it less distracting, but keep it as focal point?

We can add two call to action buttons to a relevant info on the same page. 
But, is that necessary? What action(s) would you add?

@ScintillaLuz @jancborchardt @simonv3, I didn't notice that the logo was already 'taken care of'. I'm sure @ScintillaLuz will do a great job :). 
 I'll try to remove my suggestions, to keep this clean.

**Comment by simonv3** [comment]
@MariekevC It's not taken care of! I was just saying that the reason that I put it in as just a circle was to show that we don't need to be stuck on the Open Source O logo we currently have. I'm open to ideas.

**Comment by elioqoshi** [comment]
Love the proposals shown here, I agree the first 'Marketing-ish' one might suit more, but as @bnvk  said, we could mix it a bit more with the more functional version.

**Comment by MariekevC** [comment]
@simonv3 :+1:  
I like the idea of a venn diagram (maybe also nice input for a logo?)

**Comment by MariekevC** [comment]
Some input for the OSD logo, based on the venn idea 

![osd_logo_venn](https://cloud.githubusercontent.com/assets/6065633/8058252/83ca6f4e-0eb8-11e5-9399-dfea4c805a52.png)

Left: the design part (a brush as example), 
Right: the code part ( {} as example), 
Middle: the open source icon.

**Comment by jancborchardt** [comment]
Nice @simonv3! cc @bnvk – instead of putting the two paragraphs "We are a community..." and "We provide resources..." side by side I would make the first one bigger & more present. Also both should be a bit wider so it’s more readable.

As for the logo I think we should keep it very very simple. Similar to what Open Source Hardware did:
![](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Open-source-hardware-logo.svg/200px-Open-source-hardware-logo.svg.png)

**Comment by jdittrich** [comment]
some input (rather sketchy, nowhere near usable): 
![osdlogos2](https://cloud.githubusercontent.com/assets/3416487/8061486/5504bf3a-0ecb-11e5-9f07-9903dd2b2d8b.png)
The idea behind the left one is probably obvious (we could make the circle dark so the negative/positive is a coherent thing), for the right one I played around with the idea of a logo showing "in the making".

**Comment by simonv3** [comment]
Could we move the logo convo to another thread? ;)

**Comment by plastelina** [comment]
That would be handy @simonv3 :). Do we have to use the open source logo as an starting point? Small input for the logo ( I really like what @MariekevC but I think it's to big with too much information) - still working on the idea how to incorporate it into open source logo 
![coding_design_icon](https://cloud.githubusercontent.com/assets/7548189/8062660/c992bf26-0ec8-11e5-8015-2225f1daee10.png)

**Comment by plastelina** [comment]
I just found this - not sure who had design it but it's genius http://opensourcedesign.net/images/design-open-logo-512.png

**Comment by simonv3** [comment]
Hey @plastelina, @MariekevC, @jdittrich, could you continue the conversation about logos in #18?

**Comment by jancborchardt** [comment]
@plastelina that’s the logo of http://opendesign.foundation – we wanted to use that but that wasn’t very fruitful, see https://github.com/opensourcedesign/jobs/issues/26 so we need a separate one.

**Comment by razetime** [comment]
So, is the front page layout set, or not?

**Comment by bnvk** [comment]
I think moving to the layout @simonv3 showed in [his above comment](https://github.com/opensourcedesign/opensourcedesign.github.io/issues/17#issuecomment-107081461) would be a significant improvement over the current site

To that end, since none of us are working on this full time (in order to make maximum progress with minimum effort). Perhaps we should consider customizing / modifying something from [Jekyll Themes](http://jekyllthemes.org). Personally, I think [Grayscale](http://jeromelachaud.github.io/grayscale-theme/) is quite nice and could be best tweaked towards our goals.

**Comment by simonv3** [comment]
I can do a PR for this for the front page, but changing all the styles and headers for all the other pages is going to be a bit of a pain.
