### ISSUE TITLE
Have a gitter chatroom for discussions

### ISSUE THREAD

**Issue by sudheesh001** [opensourcedesign/opensourcedesign.github.io#56]

**Comment by simonv3** [comment]
Hey @sudheesh001, we have an IRC chat room that is pretty active. It's #opensourcedesign on freenode. chat.opensourcedesign.net redirects there. 

Here's the link: https://webchat.freenode.net/?channels=opensourcedesign

**Comment by sudheesh001** [comment]
The problems with IRC is that in university campus the IRC services are blocked due to the proxy environment and for apparent "safety reasons" when we questioned the administration.

In such a case let us not kill the IRC channel but why not have a gitter room too and bridge the IRC to it ? There is a gitter irc bridge which connects the IRC channel to a gitter chat room. Messages sent in this also end up on IRC and vice versa. I think it's something worth considering. Also it maintains the log of all the messages history making it easier in case the users time out and lose all the messages.

**Comment by simonv3** [comment]
@sudheesh001 By all means take the steps to set that up :) It's pretty loose organization wise around here, so if you think it'd be a good thing to do, and if you can get it mirrored to IRC, I think that'd be great!

**Comment by sudheesh001** [comment]
@simonv3 There's a 2 way bridge that's set up between IRC and Gitter but it looks like the gitter channel is flooded with my profile though it's multiple users posting because of an exisitng gitter issue
https://github.com/gitterHQ/gitter/issues/1076

I've spoken to the teams at sameroom and they've offered to provide us an unlimited 2 way IRC-Gitter bridge using their servers.

**Comment by pdurbin** [comment]
@sudheesh001 thanks for setting up the bridge between IRC and Gitter but rather than using your personal account (sudheesh001), would you be able to change it to be an account that isn't tied to an individual and that indicates its purpose such as "gitterbot-osd" or something? Right now it looks your person account is talking (rather than [GarthDB](https://botbot.me/freenode/opensourcedesign/msg/72897409/) or others):

![irc_logs_for_ opensourcedesign_botbot me_ o_o _-_2016-09-13_08 31 58](https://cloud.githubusercontent.com/assets/21006/18473798/ddb630fc-798c-11e6-88f0-46d241ed5ed9.png)

**Comment by sudheesh001** [comment]
@pdurbin Let me have a look at that, the sameroom functionality was blocked because it looks like gitter isn't fixing https://github.com/gitterHQ/gitter/issues/1076 , let me try with the sameroom team again.

**Comment by bnvk** [comment]
I'm closing this issue seeing that A. it was implemented. B. if I understand correctly it still exists C. we now also have [chat.opensourcedesign.net](https://chat.opensourcedesign.net) which i'm committed to keeping running.

**Comment by grahamperrin** [comment]
Without reopening this issue: I'd like to help Gitter work, well, for OSD sooner rather than later during [the countdown to open sourcing of Gitter](https://about.gitlab.com/2017/03/15/gitter-acquisition/). 

@sudheesh001 thanks; at https://gitter.im/gitterHQ/gitter?at=58cd04e8fa8a98870455d6ab – an example involving Matrix – I, too, wondered about https://github.com/gitterHQ/gitter/issues/1076 

All: ping me any time at https://gitter.im/gitterHQ/gitter 

In the meantime, I see: 

- https://gitter.im/opensourcedbot_twitter related to https://twitter.com/opensourcedbot with the familiar OSD logo
- https://gitter.im/OSD-Labs which I have joined, however this *OSD…* is associated with a different OSD organisation, https://github.com/OSDLabs
- https://gitter.im/opensourcedesignbot with the familiar OSD logo, however I should refrain from promoting an organisation with _bot_ in its name.

**Comment by sudheesh001** [comment]
The last time I made changes to the bridge, I used the `opensourcedesignbot` as the account that makes the entries on gitter from IRC and that's why the gitter room https://gitter.im/opensourcedesign is not filled with the bot account than my personal account which was being used before. It'd be great to have gitter look into this and make any changes which could make the integrations much better 👍

**Comment by bnvk** [comment]
I advocate against a Gitter room for the following reasons:

- It's another channel to follow (only works if there's a critical mass)
- Requires a Github / Twitter account
- Is developer centric
- Not something one runs on their own server / easily hackable

Not sure if you're away, I recently setup [chat.opensourcedesign.net](https://chat.opensourcedesign.net)
which is a nice web IRC client. 

If OSD as a community decides IRC is overall undesirable, I would advocate for: 

- A Matrix server / channel
- Or using Rocket.chat

**Comment by grahamperrin** [comment]
> - Requires a Github / Twitter account

True at this time, but please note: 

>> we will be integrating deeper with GitLab to allow the same functionality for login, creating and joining communities from GitLab.com.

----

> Is developer centric

True, although – as an end user of software (I'm not a developer) – when I'm in the rooms that are oriented to end-users (that are not developer-centric), it's easy to close the sidebar view of commits etc..

---

> …  recently setup [chat.opensourcedesign.net] …

I can't use it; please see https://github.com/opensourcedesign/organization/issues/70#issuecomment-287533748

Thanks

**Comment by elioqoshi** [comment]
I'm also against a Gitter channel for the reasons @bnvk mentioned. However, there is currently no reason to switch to Matrix either, as Matrix users can join the IRC channel, but not the other way around.

**Comment by pdurbin** [comment]
I'm happy with the decision to use IRC, especially since we have public logging set up at https://botbot.me/freenode/opensourcedesign . To me, public logging is the most important feature Gitter brings to the table, but we have it already thanks to BotBot.me. (I'm not particularly interested in private logging such that Slack provides within its walled garden.)

I appreciate the sameroom experiment but if we ever want to try bridging IRC and Gitter again, here are other solutions I'm aware of:

- https://github.com/finnp/gitter-irc-bot
- https://github.com/42wim/matterbridge
